### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by elsewares** [p-e-w/language-javascript-semantic#25]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [language-javascript-semantic](https://github.com/p-e-w/language-javascript-semantic) package, v0.2.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/beh/.atom/packages/language-javascript-semantic/lib/javascript-semantic-grammar.coffee:94

TypeError: undefined is not a function
  at addToken (/Users/beh/.atom/packages/language-javascript-semantic/lib/javascript-semantic-grammar.coffee:94:31)
  at JavaScriptSemanticGrammar.module.exports.JavaScriptSemanticGrammar.tokenizeLine (/Users/beh/.atom/packages/language-javascript-semantic/lib/javascript-semantic-grammar.coffee:125:11)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:488:28)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:477:19)
  at TokenizedBuffer.module.exports.TokenizedBuffer.tokenizeNextChunk (/Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:265:43)
  at /Applications/Atom.app/Contents/Resources/app/src/tokenized-buffer.js:247:26
  at /Applications/Atom.app/Contents/Resources/app/node_modules/underscore-plus/node_modules/underscore/underscore.js:666:47

```

### Commands

```
  6x -6:11.8 core:select-right (atom-text-editor.editor.mini)
     -6:08.8 core:confirm (atom-text-editor.editor.mini)
  2x -5:50.3 editor:newline (atom-text-editor.editor)
  2x -5:49.0 core:backspace (atom-text-editor.editor)
     -5:47.9 editor:newline (atom-text-editor.editor)
     -5:43.8 core:backspace (atom-text-editor.editor)
     -5:37.3 core:move-right (atom-text-editor.editor)
  4x -5:36.5 editor:newline (atom-text-editor.editor)
  2x -5:20.0 core:move-down (atom-text-editor.editor)
  7x -5:18.2 core:backspace (atom-text-editor.editor)
     -5:15.0 editor:newline (atom-text-editor.editor)
  5x -5:13.5 core:backspace (atom-text-editor.editor)
     -5:10.6 editor:newline (atom-text-editor.editor)
  5x -5:06.1 core:backspace (atom-text-editor.editor)
     -4:10.5 window:update-available (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-ui.theme-atom-dark-syntax.find-visible)
  3x -3:36.6 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.0
color-picker, v1.7.0
command-logger, v0.23.0
docblockr, v0.7.2
editor-stats, v0.17.0
javascript-snippets, v1.0.0
language-javascript-better, v1.5.0
language-javascript-semantic, v0.2.1
language-lua, v0.9.3
linter, v0.12.6
minimap, v4.9.4
php-checkstyle, v0.15.0
runcoderun, v0.5.1
slash-closer, v0.7.1
visual-bell, v1.0.0

# Dev
No dev packages
```

**Comment by p-e-w** [comment]
0.187.0 is quite old. Does this error still occur with the latest version of Atom?
